# This is an example of the DAITSS configuration file restricted to
# the data necessary to run the xmlresolution service.
#
# You must set up your web server to set the environment variable
# DAITSS_CONFIG to point to a configuration file along these lines,
# though typically it will have sections for many services in addition
# to this one.
#
# Please don't use tabs in this file.

defaults:
     temp_directory:             /var/tmp

# We normally name sections after the virtual hostname used by an
# applcation (this is so one physical host can run multiple services
# of the same kind).  An application's configuration code typically
# checks the VIRTUAL_HOSTNAME environment variable to determine the
# appropriate section to load.  Typically VIRTUAL_HOSTNAME is set in
# the same place that the DAITTS_CONFIG environment is set.

xmlresolution.example.org:
     data_root:                  /var/daitss/xmlresoluition
     log_syslog_facility:        LOG_LOCAL0
     log_filename:               /path/to/name/of/file.log
     resolver_proxy:             squid.example.org:3128

# defaults:temp_directory
# -----------------------
# Where should temporary files be created? This should be at least
# twice the size of the largest package you plan to ingest, plus
# headroom.  Defaults to system-defined temp directory (typically
# /tmp/)
#

# xmlresolution:log_syslog_facility
# -------------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf). If neither log_filename nor log_syslog_facility
# are set, log to STDERR.
#
# xmlresolution:log_filename
# -------------------------------
# If set, direct log information to this file. If neither log_filename
# nor log_syslog_facility are set, log to STDERR.
#
# xmlresolution:resolver_proxy
# ----------------------------
# To avoid slamming the hosts of schema files (such as W3C, who may
# blacklist you), we recommend using a caching proxy such as squid.
# The resolver_proxy settings points to such a proxy; it is also much
# faster.
#
# xmlresolution:data_root
# -----------------------
# The directory where we'll keep data files; old files are aged out
# automatically.  If not set, the service will try to use the 'data'
# subdirectory in the installation root.  N.B.: this directory must
# have two subdirectories in it, names 'collections' and 'schemas',
# and they must be writable by the user running the service.
#

